version: '3'
services:
  eventuate-cdc-service:
    build: ./eventuate-cdc-service
    ports:
      - "8099:8080"
    depends_on:
      - postgres
      - kafka
      - redis
      - zookeeper
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/eventuate
      SPRING_DATASOURCE_USERNAME: eventuate
      SPRING_DATASOURCE_PASSWORD: eventuate
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATELOCAL_CDC_READER_NAME: PostgresWalReader
      EVENTUATE_OUTBOX_ID: 1
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      EVENTUATE_REDIS_SERVERS: redis:6379
      EVENTUATE_REDIS_PARTITIONS: 1
      EVENTUATE_CDC_TYPE: ${EVENTUATE_CDC_TYPE}
