version: '3'
services:
  eventuate-cdc-service:
    build: ./eventuate-cdc-service
    ports:
      - "8099:8080"
    depends_on:
      - mssql
      - kafka
      - zookeeper
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://mssql:1433;databaseName=eventuate
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: Eventuate123!
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.microsoft.sqlserver.jdbc.SQLServerDriver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATELOCAL_CDC_READER_NAME: MsSqlReader
      EVENTUATE_OUTBOX_ID: 1
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}

      EVENTUATE_CDC_CLEANER_1_PIPELINE: default
      EVENTUATE_CDC_CLEANER_1_MESSAGE_CLEANING_ENABLED: "true"
      EVENTUATE_CDC_CLEANER_1_MESSAGES_MAX_AGE_IN_SECONDS: 1
      EVENTUATE_CDC_CLEANER_1_INTERVAL_IN_SECONDS: 1