version: '3'
services:
  eventuate-cdc-service:
    build: ./eventuate-cdc-service
    ports:
      - "8099:8080"
    depends_on:
      - mysqlbinlogpipeline
      - postgrespollingpipeline
      - postgreswalpipeline
      - kafka
      - zookeeper
    environment:
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}

      EVENTUATE_CDC_READER_MYSQLREADER_TYPE: mysql-binlog
      EVENTUATE_CDC_READER_MYSQLREADER_DATASOURCEURL: jdbc:mysql://mysqlbinlogpipeline:3306/eventuate
      EVENTUATE_CDC_READER_MYSQLREADER_DATASOURCEUSERNAME: mysqluser
      EVENTUATE_CDC_READER_MYSQLREADER_DATASOURCEPASSWORD: mysqlpw
      EVENTUATE_CDC_READER_MYSQLREADER_DATASOURCEDRIVERCLASSNAME: com.mysql.cj.jdbc.Driver
      EVENTUATE_CDC_READER_MYSQLREADER_LEADERSHIPLOCKPATH: /eventuatelocal/cdc/leader/pipeline/1
      EVENTUATE_CDC_READER_MYSQLREADER_CDCDBUSERNAME: root
      EVENTUATE_CDC_READER_MYSQLREADER_CDCDBPASSWORD: rootpassword
      EVENTUATE_CDC_READER_MYSQLREADER_READOLDDEBEZIUMDBOFFSETSTORAGETOPIC: "false"
      EVENTUATE_CDC_READER_MYSQLREADER_MYSQLBINLOGCLIENTUNIQUEID: 1234567890
      EVENTUATE_CDC_READER_MYSQLREADER_OUTBOXID: 1
      EVENTUATE_CDC_READER_MYSQLREADER_OFFSETSTOREKEY: MySqlBinlog

      EVENTUATE_CDC_READER_POSTGRESPOLLINGREADER_TYPE: polling
      EVENTUATE_CDC_READER_POSTGRESPOLLINGREADER_DATASOURCEURL: jdbc:postgresql://postgrespollingpipeline/eventuate
      EVENTUATE_CDC_READER_POSTGRESPOLLINGREADER_DATASOURCEUSERNAME: eventuate
      EVENTUATE_CDC_READER_POSTGRESPOLLINGREADER_DATASOURCEPASSWORD: eventuate
      EVENTUATE_CDC_READER_POSTGRESPOLLINGREADER_DATASOURCEDRIVERCLASSNAME: org.postgresql.Driver
      EVENTUATE_CDC_READER_POSTGRESPOLLINGREADER_OUTBOXID: 2
      EVENTUATE_CDC_READER_POSTGRESPOLLINGREADER_LEADERSHIPLOCKPATH: /eventuatelocal/cdc/leader/pipeline/2

      EVENTUATE_CDC_READER_POSTGRESWALREADER_TYPE: postgres-wal
      EVENTUATE_CDC_READER_POSTGRESWALREADER_DATASOURCEURL: jdbc:postgresql://postgreswalpipeline/eventuate
      EVENTUATE_CDC_READER_POSTGRESWALREADER_DATASOURCEUSERNAME: eventuate
      EVENTUATE_CDC_READER_POSTGRESWALREADER_DATASOURCEPASSWORD: eventuate
      EVENTUATE_CDC_READER_POSTGRESWALREADER_DATASOURCEDRIVERCLASSNAME: org.postgresql.Driver
      EVENTUATE_CDC_READER_POSTGRESWALREADER_OUTBOXID: 3
      EVENTUATE_CDC_READER_POSTGRESWALREADER_LEADERSHIPLOCKPATH: /eventuatelocal/cdc/leader/pipeline/3

      EVENTUATE_CDC_PIPELINE_P1_TYPE: eventuate-local
      EVENTUATE_CDC_PIPELINE_P1_READER: MYSQLREADER

      EVENTUATE_CDC_PIPELINE_P2_TYPE: eventuate-local
      EVENTUATE_CDC_PIPELINE_P2_READER: POSTGRESPOLLINGREADER

      EVENTUATE_CDC_PIPELINE_P3_TYPE: eventuate-local
      EVENTUATE_CDC_PIPELINE_P3_READER: POSTGRESWALREADER

      EVENTUATE_CDC_PIPELINE_P4_TYPE: eventuate-tram
      EVENTUATE_CDC_PIPELINE_P4_READER: MYSQLREADER

      EVENTUATE_CDC_PIPELINE_P5_TYPE: eventuate-tram
      EVENTUATE_CDC_PIPELINE_P5_READER: POSTGRESPOLLINGREADER

      EVENTUATE_CDC_PIPELINE_P6_TYPE: eventuate-tram
      EVENTUATE_CDC_PIPELINE_P6_READER: POSTGRESWALREADER

      EVENTUATE_CDC_CLEANER_C1_PIPELINE: P4
      EVENTUATE_CDC_CLEANER_C1_MESSAGE_CLEANING_ENABLED: "true"
      EVENTUATE_CDC_CLEANER_C1_MESSAGES_MAX_AGE_IN_SECONDS: 1
      EVENTUATE_CDC_CLEANER_C1_INTERVAL_IN_SECONDS: 1

      EVENTUATE_CDC_CLEANER_C2_PIPELINE: P5
      EVENTUATE_CDC_CLEANER_C2_MESSAGE_CLEANING_ENABLED: "true"
      EVENTUATE_CDC_CLEANER_C2_MESSAGES_MAX_AGE_IN_SECONDS: 1
      EVENTUATE_CDC_CLEANER_C2_INTERVAL_IN_SECONDS: 1

      EVENTUATE_CDC_CLEANER_C3_DATASOURCE_URL: jdbc:postgresql://postgreswalpipeline/eventuate
      EVENTUATE_CDC_CLEANER_C3_DATASOURCE_USERNAME: eventuate
      EVENTUATE_CDC_CLEANER_C3_DATASOURCE_PASSWORD: eventuate
      EVENTUATE_CDC_CLEANER_C3_DATASOURCE_DRIVER_CLASSNAME: org.postgresql.Driver
      EVENTUATE_CDC_CLEANER_C3_MESSAGE_CLEANING_ENABLED: "true"
      EVENTUATE_CDC_CLEANER_C3_MESSAGES_MAX_AGE_IN_SECONDS: 1
      EVENTUATE_CDC_CLEANER_C3_INTERVAL_IN_SECONDS: 1