version: '3'
services:
  eventuate-cdc-service:
    image: ${EVENTUATE_CDC_SERVICE_MULTI_ARCH_IMAGE:-localhost:5002/eventuate-cdc-service:multi-arch-local-build}
    ports:
      - "8099:8080"
    depends_on:
      - mysql
      - kafka
      - zookeeper
      - activemq
      - rabbitmq
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATELOCAL_CDC_DB_USER_NAME: root
      EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword
      EVENTUATELOCAL_CDC_READER_NAME: MySqlReader
      EVENTUATE_OUTBOX_ID: 1
      EVENTUATELOCAL_CDC_MYSQL_BINLOG_CLIENT_UNIQUE_ID: 1234567890
      EVENTUATELOCAL_CDC_READ_OLD_DEBEZIUM_DB_OFFSET_STORAGE_TOPIC: "false"
      EVENTUATE_CDC_TYPE: ${EVENTUATE_CDC_TYPE}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      ACTIVEMQ_URL: tcp://activemq:61616
      ACTIVEMQ_USER: eventuateuser
      ACTIVEMQ_PASSWORD: eventuatepassword
      RABBITMQ_BROKER_ADDRESSES: rabbitmq
      EVENTUATE_REDIS_SERVERS: redis:6379
      EVENTUATE_REDIS_PARTITIONS: 1
